name: Run MS Teams Dummy Participants

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-dummy-participants:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK (assumes your project uses .NET SDK)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Adjust this version based on your project's .NET version

      # Step 3: Install Chrome and ChromeDriver (necessary for Selenium)
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromedriver

      # Step 4: Install project dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 5: Build the project
      - name: Build project
        run: dotnet build --configuration Release

      # Step 6: Run tests or start the participant runner (specify parameters)
      - name: Run Dummy Participants
        run: |
          # Set up environment variables for meeting details and participant count
          echo "MEETING_ID=938 808 388 348 5" >> $GITHUB_ENV
          echo "MEETING_PASSWORD=YW2eJ9" >> $GITHUB_ENV
          echo "PARTICIPANT_COUNT=10" >> $GITHUB_ENV

          # Run the participant runner
          dotnet run --configuration Release

      # Optional: Step 7 - Clean up (if needed)
      - name: Clean up
        run: |
          sudo apt-get remove -y chromium-browser chromedriver
          sudo apt-get autoremove -y
