name: Run MS Teams Dummy Participants

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-dummy-participants:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK (assumes your project uses .NET SDK)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Adjust this version based on your project's .NET version

      # Step 3: Install Chromium (Headless browser)
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      # Step 4: Install ChromeDriver manually (matching the Chromium version)
      - name: Install ChromeDriver
        run: |
          # Define the desired Chromium version
          CHROMIUM_VERSION=$(chromium-browser --version | awk '{print $2}')
          # Download the appropriate version of ChromeDriver from the official site
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          # Unzip the downloaded chromedriver
          unzip chromedriver_linux64.zip
          # Move the chromedriver binary to /usr/local/bin
          sudo mv chromedriver /usr/local/bin/

      # Step 5: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 6: Build project
      - name: Build project
        run: dotnet build --configuration Release

      # Step 7: Run the Dummy Participant Application
      - name: Run Dummy Participants
        run: |
          # Set environment variables for the meeting and participant details
          echo "MEETING_ID= 938 808 388 348 5" >> $GITHUB_ENV
          echo "MEETING_PASSWORD= YW2eJ9" >> $GITHUB_ENV
          echo "PARTICIPANT_COUNT=10" >> $GITHUB_ENV

          # Run the participant runner
          dotnet run --configuration Release

      # Optional: Step 8 - Clean up (if needed)
      - name: Clean up
        run: |
          sudo apt-get remove -y chromium-browser
          sudo apt-get autoremove -y
