name: Run Teams Dummy Participants

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Specify the .NET version

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet add package Selenium.WebDriver
          dotnet add package Selenium.WebDriver.ChromeDriver

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          sudo apt install -y chromium-chromedriver

      - name: Run the C# Script
        run: |
          dotnet build
          dotnet run
        env:
          MEETING_ID: ${{ secrets.MEETING_ID }}  # GitHub Secret for the meeting ID
          MEETING_PASSWORD: ${{ secrets.MEETING_PASSWORD }}  # GitHub Secret for the password
          PARTICIPANT_COUNT: ${{ secrets.PARTICIPANT_COUNT }}  # GitHub Secret for participant count
          DISPLAY: :99.0  # Headless display setup for CI/CD environment
          CHROME_BIN: /usr/bin/chromium-browser  # Path to Chromium
          CHROME_PATH: /usr/lib/chromium-browser/chromedriver  # Path to ChromeDriver
